---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  annotations:
    release.openshift.io/version: "{{.ReleaseVersion}}"
spec:
  selector:
    matchLabels:
      app: ovsdpdk-network-prepare
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ovsdpdk-network-prepare
        component: network
        type: infra
        openshift.io/component: network
    spec:
      hostNetwork: true
      nodeSelector:
        {{range $index, $element := .NodeSelector}}{{$index}}: "{{$element}}"{{end}}
      tolerations:
      - operator: Exists
      serviceAccountName: ovsdpdk-network-operator
      initContainers:
      - name: {{.Name}}-init
        image: {{.ImageInit}}
        volumeMounts:
        - name: cni-bin
          mountPath: /cni
      containers:
      - name: {{.Name}}
        image: {{.Image}}
        command:
          - ovsdpdk-network-prepare
        imagePullPolicy: Always
        securityContext:
          privileged: true
        args:
          - "--v=3"
          - "start"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OVSDPDK_PREAPE_CONFIG_MAP
            value: {{.Name}}
        volumeMounts:
        - name: hostsys
          mountPath: /host/sys
        - name: ovsrun
          mountPath: /var/run/openvswitch
      volumes:
      - name: hostsys
        hostPath:
          path: /sys
      - name: ovsrun
        hostPath:
          path: /var/run/openvswitch
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin/
