apiVersion: ovsdpdknetwork.openshift.io/v1
kind: OvsDpdkConfig
metadata:
  name: example-ovsdpdkconfig
spec:
  nodeSelectorLabels:
    network.operator.openshift.io/external-openvswitch: ""
  nodeConfig:
    pmdCount: 1
  interfaceConfig:
    - bridge: "br-dpdk0"
      bond: false
      nicSelector:
        devices:
          - 0000:06:00.0
