apiVersion: ovsdpdk.network.openshift.io/v1
kind: OvsDpdkConfig
metadata:
  name: ovsdpdk-group-1
spec:
  nodeSelector:
    network.operator.openshift.io/external-openvswitch: ""
  nodeConfig:
    pmdCount: 1
  interfaceConfig:
    - bridge: "br-dpdk0"
      bond: false
      nicSelector:
        devices:
          - 0000:06:00.0

